source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Disketta_Example', :exclusive => true do
  pod "Disketta", :path => "../"
end

target 'Disketta_Tests', :exclusive => true do
  pod "Disketta", :path => "../"

  
end
